#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# Displays "Hi" at 9th iteration.

counter=1

while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
