#!/usr/bin/env bash
# Displays numbers 1 to 20 using a while loop.
# Displays "bad luck for China" and "bad luck Japan"
# after 4th, 9th and 17th iteration respectively.

counter=1
while [ $counter -le 20 ]
do
    echo "$counter"
    case $counter in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    ((counter++))
done
